CREATE DATABASE doingsdone_db
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE doingsdone_db;

CREATE TABLE project (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_name VARCHAR(128)
);

CREATE TABLE task (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_add TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  task_status BOOLEAN DEFAULT 0,
  task_name VARCHAR(128),
  task_url VARCHAR(128),
  task_due_dt TIMESTAMP
);

CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dt_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(128),
  usr_name VARCHAR(128),
  user_password CHAR(64)
);
